[build]
  publish = "public"
  functions = "api/netlify/functions"
  command = "cd api/netlify && npm install"

[template.environment]
  RECURLY_API_KEY = "f5c2bba23cbd45769a9d367acea5187c"
  RECURLY_PUBLIC_KEY = "ewr1-v03AcvcQWcmHukoACKbbo1"
  SUCCESS_URL = "Redirect URL for new suscription success"
  ERROR_URL = "Redirect URL for new subscription error"

[[redirects]]
  from = "/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/subscriptions/new"
  to = "/.netlify/functions/new-subscription"
  status = 200

[[redirects]]
  from = "/api/accounts/new"
  to = "/.netlify/functions/new-account"
  status = 200

[[redirects]]
  from = "/api/accounts/:account"
  to = "/.netlify/functions/update-account/:account"
  status = 200
